# Copyright (c) 2023-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/test.gni")

group("core_unittest") {
  testonly = true
  deps = []
  if (is_host_product) {
    deps += [
      "base:frame_node_drop_test_ng",
      "base:short_cuts_little_test_ng",
      "base:short_cuts_test_ng",
      "base:transparent_node_detector_test_ng",
      "base:view_abstract_model_test_ng",
      "base:view_abstract_test_resetposition_ng",
      "base:view_full_update_model_ng_test",
      "base:view_partial_update_model_test_ng",
      "base:view_stack_processor_test_ng",
      "common/key_event_manager:key_event_manager_test",
      "common/recorder:event_recorder_test",
      "event:axis_event_test_ng",
      "event:click_event_test_ng",
      "event:coasting_axis_event_test_ng",
      "event:drag_drop_event_test_ng",
      "event:drag_event_test_ng",
      "event:drag_event_test_ng_base",
      "event:event_hub_test_ng",
      "event:event_manager_test_ng",
      "event:focus_box_test_ng",
      "event:focus_event_handler_test_ng",
      "event:focus_hub_test_ng",
      "event:gesture_event_hub_test_ng",
      "event:input_event_hub_test_ng",
      "event:input_event_monitor_manager_test_ng",
      "event:input_event_test_ng",
      "event:key_event_test_ng",
      "event:long_press_event_test_ng",
      "event:mouse_style_manager_test_ng",
      "event:pan_event_test_ng",
      "event:response_ctrl_test_ng",
      "event:state_style_test_ng",
      "event:touch_event_test_ng",
      "gestures:gestures_test_ng",
      "manager:active_recognizer_manager_test_ng",
      "manager:drag_animation_helper_test_ng",
      "manager:drag_drop_behavior_reporter_test_ng",
      "manager:drag_drop_controller_func_wrapper_test_ng",
      "manager:drag_drop_func_wrapper_test_ng",
      "manager:drag_drop_initiating_state_test_ng",
      "manager:drag_drop_manager_test_ng",
      "manager:drag_drop_proxy_test_ng",
      "manager:drag_drop_report_test_ng",
      "manager:drag_drop_spring_loading_test_ng",
      "manager:focus_manager_test_ng",
      "manager:focus_view_test_ng",
      "manager:gesture_debug_boundary_manager_test_ng",
      "manager:json_report_test_ng",
      "manager:post_event_manager_test_ng",
      "manager:shared_overlay_manager_test_ng",
      "manager:smart_gesture_decider_test_ng",
      "manager:smart_gesture_manager_test_ng",
      "pattern:core_pattern_unittest",
      "pattern/relaxed_interaction:relaxed_interaction_manager_test_ng",
      "property:property_test_ng",
    ]
  } else {
    deps = [
      "accessibility:core_accessibility_unittest",
      "animation:core_animation_unittest",
      "base:core_base_unittest",
      "common:core_common_unittest",
      "components:core_components_unittest",
      "event:core_event_unittest",
      "gestures:gestures_test_ng",
      "image:image_file_cache_test_ng",
      "image:image_loader_test",
      "image:image_provider_test_ng",
      "interfaces:core_interfaces_unittest",
      "layout:core_layout_unittest",
      "manager:core_manager_unittest",
      "pattern:core_pattern_unittest",
      "pipeline:pipeline_context_test_ng",
      "property:core_property_unittest",
      "render:core_render_unittest",
      "rosen:arkui_rosen_render_context_test",
      "rosen:gradient_style_modifier_test",
      "svg:core_svg_unittest",
      "syntax:core_syntax_unittest",
    ]
  }
}
