// This file has been autogenerated. Do not update manually.
import { EntryExample as Entry0 } from "./Rewrite"
import { LocalStorageLinkExample as Entry1 } from "./Rewrite2"
import { LocalStoragePropExample as Entry2 } from "./Rewrite3"
import { DollarDollar as Entry3 } from "./dollar-dollar/components"
import { Index as Entry4 } from "./dollar-functions/dollar-functions"

export function registerRoutes() {
	const __forceEntry0Use = Entry0
	const __forceEntry1Use = Entry1
	const __forceEntry2Use = Entry2
	const __forceEntry3Use = Entry3
	const __forceEntry4Use = Entry4
}
