/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package arkui.component.idlize;

import arkui.component.imageCommon.ImageAnalyzerConfig as ImageAnalyzerConfig;
import arkui.component.xcomponent.XComponentController as XComponentController;
import arkui.component.xcomponent.SurfaceRect as SurfaceRect;
import arkui.component.xcomponent.SurfaceConfig as SurfaceConfig;
import arkui.component.xcomponent.SurfaceRotationOptions as SurfaceRotationOptions;
import arkui.component.units.DrawingCanvas as DrawingCanvas;

[Entity=Class]
interface XComponentControllerExtender {
    static Promise<void> startImageAnalyzer(XComponentController peer, ImageAnalyzerConfig config);
};

callback OnSurfaceCreatedCb = void (String surfaceId);
callback OnSurfaceChangedCb = void (String surfaceId, SurfaceRect rect);
callback OnSurfaceDestroyedCb = void (String surfaceId);

interface XComponentControllerWrapper {
    attribute Object managed;
    attribute XComponentControllerNative nativeObj;
    attribute OnSurfaceCreatedCb onSurfaceCreated;
    attribute OnSurfaceChangedCb onSurfaceChanged;
    attribute OnSurfaceDestroyedCb onSurfaceDestroyed;
};

[Entity=Class]
interface XComponentControllerNative {
    constructor();
    String getXComponentSurfaceId();
    void setXComponentSurfaceRect(SurfaceRect rect);
    SurfaceRect getXComponentSurfaceRect();
    void setXComponentSurfaceRotation(SurfaceRotationOptions rotationOptions);
    SurfaceRotationOptions getXComponentSurfaceRotation();
    void stopImageAnalyzer();
    (DrawingCanvas or idlize.stdlib.Null) lockCanvas();
    void unlockCanvasAndPost(DrawingCanvas canvas);
    void setXComponentSurfaceConfig(SurfaceConfig config);
};
