/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package arkui.component.idlize;
import arkui.Graphics.LengthMetrics as LengthMetrics;
import arkui.component.common.OnVisibleIndexesChangeCallback as OnVisibleIndexesChangeCallback;
import arkui.component.units.ItemFillPolicy as ItemFillPolicy;
import arkui.component.list.StickyStyle as StickyStyle;
[Entity=Class]
interface LazyWaterFlowLayoutExtender {
    static pointer lazyVWaterFlowLayoutConstructor(i32 id);
    static void setLazyVWaterFlowLayoutOptions(pointer node);
    static void rowsGap(pointer node, optional LengthMetrics value);
    static void columnsGap(pointer node, optional LengthMetrics value);
    static void columnsTemplate(pointer node, (String or ItemFillPolicy or undefined) value);
    static void header(pointer node, optional CustomBuilder builder);
    static void footer(pointer node, optional CustomBuilder builder);
    static void sticky(pointer node, optional StickyStyle sticky);
    static void onVisibleIndexesChange(pointer node, optional OnVisibleIndexesChangeCallback callback_);
};
